# Generated by Django 5.1.2 on 2025-04-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asistencia',
            new_name='Detectado',
        ),
    ]
