# Generated by Django 5.1.2 on 2025-04-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_asistencia_detectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateField(auto_created=True)),
                ('nombre', models.CharField(max_length=100)),
                ('informacion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='registrados/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
