# Generated by Django 5.1.2 on 2025-04-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_registrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='actualizado_en',
            field=models.DateField(auto_now=True),
        ),
    ]
